title: Pair Blog
baseurl: "/pair-blog"  # Adjust if needed
future: true
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
plugins:
  - jekyll-remote-theme
header_pages:
- _notebooks/Foundation/C-github_pages/intro.md
- _notebooks/Foundation/C-github_pages/jokes.md
- _notebooks/Foundation/C-github_pages/tracking.md
